/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Arvore.java
 *
 * Created on 11/09/2010, 11:13:26
 */

package aula3;

import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author david
 */
public class Arvore extends javax.swing.JFrame {

    /** Creates new form Arvore */
    public Arvore() {
        initComponents();

        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Raiz");

        DefaultMutableTreeNode filho1 = new DefaultMutableTreeNode("Filho 1");
        DefaultMutableTreeNode filho2 = new DefaultMutableTreeNode("Filho 2");

        raiz.add(filho1);
        raiz.add(filho2);

        DefaultMutableTreeNode neto1 = new DefaultMutableTreeNode("Neto 1");
        DefaultMutableTreeNode neto2 = new DefaultMutableTreeNode("Neto 2");
        
        filho1.add(neto1);
        filho1.add(neto2);

        DefaultMutableTreeNode neto3 = new DefaultMutableTreeNode("Neto 3");
        filho2.add(neto3);

        jTree1.setModel(new DefaultTreeModel(raiz));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arvore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

}
